### ISSUE TITLE
Places to Discuss and get some advice?

### ISSUE THREAD

**Issue by SirNibble** [prirun/p50em#6]
Ok, not really an Issue, per-se, but is there anywhere to discuss the emulator and get some help and advice?

Have the emulaor running as a 9955ii Rev 20 on a Pi4 and now having loads of fun getting to be how my aged memory tells me it was when I looked after one for the Ministry of Agriculture, Fisheries and Food in the UK. 

Thanks to all involved in getting this to work.

**Comment by drboone** [comment]
For now, feel free to open issues if you need help.  Right now the closest thing to a place is probably the usenet group comp.sys.prime.

Looks like github discussions are available to us now, so we could talk about doing that.  Jim, thoughts?

**Comment by hashbackup** [comment]
Fine with me.

**Comment by drboone** [comment]
Ok, I've enabled that.

**Comment by SirNibble** [comment]
Thanks, Gentlemen.
